In [32]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import PolynomialFeatures

In [33]:
#load file 
df = pd.read_csv('response indo.csv')
df

Age (umur) Occupation (Pekerjaan)  Music  Slow songs or fast songs  Dance  \
0           19              Mahasiswa      3                         3      1   
1           19              Mahasiswa      5                         3      5   
2           20              Mahasiswa      5                         2      1   
3           19              Mahasiswa      5                         2      3   
4           19              Mahasiswa      5                         3      4   
..         ...                    ...    ...                       ...    ...   
70          20              Mahasiswa      5                         3      4   
71          20              Mahasiswa      5                         3      2   
72          20              Mahasiswa      4                         4      2   
73          21              Mahasiswa      5                         3      5   
74          19              Mahasiswa      5                         3      4   

    Folk  Country  Classical music  Musical  Pop  ...  Reggae, Ska  \
0      1        1                1        4    5  ...            1   
1      4        4                4        5    4  ...            4   
2      2        1                5        5    4  ...            1   
3      3        4                4        4    4  ...            2   
4      4        3                3        3    4  ...            3   
..   ...      ...              ...      ...  ...  ...          ...   
70     3        4                2        3    4  ...            1   
71     2        3                2        3    5  ...            3   
72     1        1                3        2    4  ...            1   
73     3        3                3        3    4  ...            3   
74     2        2                3        3    4  ...            1   

    Swing, Jazz  Rock n roll  Alternative  Latino  Techno, Trance  Opera  \
0             4            1            1       1               1      1   
1             5            5            5       4               5      4   
2             3            1            1       1               1      3   
3             5            3            3       4               3      3   
4             4            3            3       3               3      3   
..          ...          ...          ...     ...             ...    ...   
70            3            3            2       1               1      2   
71            4            3            3       4               4      4   
72            5            1            2       1               5      1   
73            3            3            5       2               4      2   
74            2            3            4       1               2      2   

           Smoking         Alcohol  Healthy eating  
0     never smoked           never               2  
1   current smoker           never               2  
2     never smoked  social drinker               5  
3     never smoked           never               4  
4     never smoked           never               4  
..             ...             ...             ...  
70    never smoked  social drinker               3  
71    never smoked           never               3  
72    never smoked  social drinker               4  
73    never smoked  social drinker               1  
74    never smoked  social drinker               3  

[75 rows x 24 columns]

In [34]:
#mengubah string menjadi angka di Smoking  
df["Smoking"] = df["Smoking"].replace('current smoker', 1)  
df["Smoking"] = df["Smoking"].replace('former smoker', 1) 
df["Smoking"] = df["Smoking"].replace('tried smoking', 0)   
df["Smoking"] = df["Smoking"].replace('never smoked', 0)
#mengubah string menjadi angka di Alcohol
df["Alcohol"] = df["Alcohol"].replace('drink a lot', 2)  
df["Alcohol"] = df["Alcohol"].replace('social drinker', 1)    
df["Alcohol"] = df["Alcohol"].replace('never', 0)

In [35]:
#drop data
newDf = df.dropna()
print(newDf.isna().values.any())

False


In [36]:
#declare dataset feature and target 
feature = newDf[["Music","Slow songs or fast songs","Dance","Folk","Country","Classical music","Musical","Pop","Rock","Metal or Hardrock","Punk","Hiphop, Rap","Reggae, Ska","Swing, Jazz","Rock n roll","Alternative","Latino","Techno, Trance","Opera"]]
target = newDf[["Smoking"]]
x, y = np.array(feature), np.array(target)

In [37]:
#mengapply PolynominalFeatures untuk selanjutnya dimasukkan ke linear regression
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [38]:
#mengfit data
transformer.fit(x)

PolynomialFeatures(degree=2, include_bias=False, interaction_only=False,
                   order='C')

In [39]:
#mengtransform input array 
x= transformer.transform(x)

In [40]:
print(x)

[[ 3.  3.  1. ...  1.  1.  1.]
 [ 5.  3.  5. ... 25. 20. 16.]
 [ 5.  2.  1. ...  1.  3.  9.]
 ...
 [ 4.  4.  2. ... 25.  5.  1.]
 [ 5.  3.  5. ... 16.  8.  4.]
 [ 5.  3.  4. ...  4.  4.  4.]]


In [41]:
#mengapply linear regression dan fit
model = LinearRegression().fit(x, y)

In [42]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)# hasil R-Squared (bila di bawah 0.5 maka feature tidak berpengaruh kepada target)
print('intercept:', model.intercept_)# hasil coefficient pada b0 (bila di atas 0.05 maka feature tidak berpengaruh kepada target)
print('slope:', model.coef_)# hasil coefficient pada bias setelah b0 yakni b1 b2 b3(bila di atas 0.05 maka feature tidak berpengaruh kepada target)

coefficient of determination: 1.0
intercept: [-0.0463684]
slope: [[ 0.00808372  0.00757386  0.01002471 -0.0107388   0.0005779   0.00420936
  -0.00932593  0.01166001  0.00321361  0.00608781  0.00041407  0.00840087
   0.00045     0.00589795  0.00231382 -0.00411976  0.00374865  0.00749977
   0.00030942 -0.01814315  0.01204316 -0.0153163  -0.0158178   0.01591896
   0.02385655  0.01396142  0.01014658 -0.01137987 -0.00188587  0.03459265
   0.00214544  0.01760964 -0.00693443 -0.03609756 -0.01352777  0.02354457
   0.02093455  0.00814546  0.01466805  0.00238866 -0.00367345  0.01644456
  -0.02075628 -0.00981198  0.04508722  0.01877691 -0.00352835 -0.01623492
  -0.02265982 -0.00289117  0.00691112  0.00884749  0.01207173 -0.02124308
  -0.02454058 -0.05406372 -0.0120788   0.00975082  0.00646362  0.0262044
  -0.0141117  -0.01833461 -0.01086633  0.04177747 -0.02399002  0.02539118
   0.01673288  0.03553395  0.01382073 -0.06305101 -0.00727539 -0.02276498
   0.04436064 -0.06164067 -0.01069052  0.0177383

In [43]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')
#memprediksi nilai nilai untuk target target

predicted response:
[[ 7.91033905e-16]
 [ 1.00000000e+00]
 [ 3.46944695e-16]
 [-2.08166817e-16]
 [ 1.40165657e-15]
 [-2.08166817e-16]
 [-4.57966998e-16]
 [-5.41233725e-16]
 [-5.41233725e-16]
 [-8.74300632e-16]
 [ 1.01307851e-15]
 [-9.71445147e-17]
 [ 9.57567359e-16]
 [-2.08166817e-16]
 [-7.63278329e-16]
 [-7.63278329e-16]
 [ 5.68989300e-16]
 [-3.19189120e-16]
 [ 1.45716772e-15]
 [-1.09634524e-15]
 [-2.30371278e-15]
 [-1.09634524e-15]
 [ 5.68989300e-16]
 [-1.65145675e-15]
 [ 1.00000000e+00]
 [ 2.23432384e-15]
 [ 2.70616862e-15]
 [ 1.00000000e+00]
 [ 1.01307851e-15]
 [-2.04003481e-15]
 [ 1.79023463e-15]
 [ 1.12410081e-15]
 [ 7.91033905e-16]
 [ 8.74300632e-16]
 [-4.57966998e-16]
 [ 1.45716772e-15]
 [-1.42941214e-15]
 [ 7.91033905e-16]
 [ 3.73312492e-15]
 [ 1.90125693e-15]
 [ 3.46944695e-16]
 [ 1.38777878e-17]
 [-1.54043445e-15]
 [ 1.23512311e-15]
 [-7.07767178e-16]
 [-1.42941214e-15]
 [-1.09634524e-15]
 [-1.42941214e-15]
 [ 1.45716772e-15]
 [ 1.38777878e-17]
 [ 1.90125693e-15]
 [-5.412337

In [44]:
print("Mean Absolute Error (MAE): ", mean_absolute_error(y, y_pred))
print("Mean Squared Error (MSE): ", mean_squared_error(y, y_pred))
print("R2: ", r2_score(y, y_pred))

Mean Absolute Error (MAE):  1.0484206095876895e-15
Mean Squared Error (MSE):  1.623276473393263e-30
R2:  1.0
