In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import PolynomialFeatures

In [4]:
#load file 
df = pd.read_csv('responses.csv')
df

Music  Slow songs or fast songs  Dance  Folk  Country  Classical music  \
0       5.0                       3.0    2.0   1.0      2.0              2.0   
1       4.0                       4.0    2.0   1.0      1.0              1.0   
2       5.0                       5.0    2.0   2.0      3.0              4.0   
3       5.0                       3.0    2.0   1.0      1.0              1.0   
4       5.0                       3.0    4.0   3.0      2.0              4.0   
...     ...                       ...    ...   ...      ...              ...   
1005    5.0                       2.0    5.0   2.0      2.0              5.0   
1006    4.0                       4.0    5.0   1.0      3.0              4.0   
1007    4.0                       3.0    1.0   1.0      2.0              2.0   
1008    5.0                       3.0    3.0   3.0      1.0              3.0   
1009    5.0                       5.0    4.0   3.0      2.0              3.0   

      Musical  Pop  Rock  Metal or Hardrock  ...   Age  Height  Weight  \
0         1.0  5.0   5.0                1.0  ...  20.0   163.0    48.0   
1         2.0  3.0   5.0                4.0  ...  19.0   163.0    58.0   
2         5.0  3.0   5.0                3.0  ...  20.0   176.0    67.0   
3         1.0  2.0   2.0                1.0  ...  22.0   172.0    59.0   
4         3.0  5.0   3.0                1.0  ...  20.0   170.0    59.0   
...       ...  ...   ...                ...  ...   ...     ...     ...   
1005      4.0  4.0   4.0                3.0  ...  20.0   164.0    57.0   
1006      1.0  4.0   1.0                1.0  ...  27.0   183.0    80.0   
1007      2.0  3.0   4.0                1.0  ...  18.0   173.0    75.0   
1008      1.0  3.0   4.0                1.0  ...  25.0   173.0    58.0   
1009      3.0  4.0   1.0                1.0  ...  21.0   185.0    72.0   

      Number of siblings  Gender  Left - right handed  \
0                    1.0  female         right handed   
1                    2.0  female         right handed   
2                    2.0  female         right handed   
3                    1.0  female         right handed   
4                    1.0  female         right handed   
...                  ...     ...                  ...   
1005                 1.0  female         right handed   
1006                 5.0    male          left handed   
1007                 0.0  female         right handed   
1008                 1.0  female         right handed   
1009                 1.0    male         right handed   

                    Education  Only child  Village - town  \
0     college/bachelor degree          no         village   
1     college/bachelor degree          no            city   
2            secondary school          no            city   
3     college/bachelor degree         yes            city   
4            secondary school          no         village   
...                       ...         ...             ...   
1005         secondary school          no            city   
1006           masters degree          no         village   
1007         secondary school         yes            city   
1008  college/bachelor degree          no            city   
1009         secondary school          no         village   

      House - block of flats  
0             block of flats  
1             block of flats  
2             block of flats  
3             house/bungalow  
4             house/bungalow  
...                      ...  
1005          house/bungalow  
1006          house/bungalow  
1007          block of flats  
1008          block of flats  
1009          house/bungalow  

[1010 rows x 150 columns]

In [5]:
#mengubah string menjadi angka di Smoking  
df["Smoking"] = df["Smoking"].replace('current smoker', 1)  
df["Smoking"] = df["Smoking"].replace('former smoker', 1) 
df["Smoking"] = df["Smoking"].replace('tried smoking', 0)   
df["Smoking"] = df["Smoking"].replace('never smoked', 0)
#mengubah string menjadi angka di Alcohol
df["Alcohol"] = df["Alcohol"].replace('drink a lot', 2)  
df["Alcohol"] = df["Alcohol"].replace('social drinker', 1)    
df["Alcohol"] = df["Alcohol"].replace('never', 0)

In [6]:
#drop data
newDf = df.dropna()
print(newDf.isna().values.any())

False


In [7]:
#declare dataset feature and target 
feature = newDf[["Music","Slow songs or fast songs","Dance","Folk","Country","Classical music","Musical","Pop","Rock","Metal or Hardrock","Punk","Hiphop, Rap","Reggae, Ska","Swing, Jazz","Rock n roll","Alternative","Latino","Techno, Trance","Opera"]]
target = newDf[["Smoking"]]
x, y = np.array(feature), np.array(target)

In [8]:
#mengapply PolynominalFeatures untuk selanjutnya dimasukkan ke linear regression
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [9]:
#mengfit data
transformer.fit(x)

PolynomialFeatures(degree=2, include_bias=False, interaction_only=False,
                   order='C')

In [10]:
#mengtransform input array 
x= transformer.transform(x)

In [11]:
print(x)

[[5. 3. 2. ... 1. 1. 1.]
 [4. 4. 2. ... 1. 1. 1.]
 [5. 5. 2. ... 1. 3. 9.]
 ...
 [4. 3. 1. ... 1. 1. 1.]
 [5. 3. 3. ... 4. 2. 1.]
 [5. 5. 4. ... 9. 3. 1.]]


In [12]:
#mengapply linear regression dan fit
model = LinearRegression().fit(x, y)

In [13]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)# hasil R-Squared (bila di bawah 0.5 maka feature tidak berpengaruh kepada target)
print('intercept:', model.intercept_)# hasil coefficient pada b0 (bila di atas 0.05 maka feature tidak berpengaruh kepada target)
print('slope:', model.coef_)# hasil coefficient pada bias setelah b0 yakni b1 b2 b3(bila di atas 0.05 maka feature tidak berpengaruh kepada target)

coefficient of determination: 0.3779313649958821
intercept: [1.40676905]
slope: [[-4.75225245e-01 -4.21922676e-01 -8.61548182e-02 -4.23567902e-01
   2.79599614e-01 -2.87169869e-01  3.49060197e-01  8.70202956e-02
   2.56760021e-01  7.98034060e-02 -3.67540422e-01  6.27684474e-02
  -1.94410822e-01 -1.54838450e-01  3.06518344e-01  2.83402875e-01
  -1.76397623e-01  4.78338349e-02 -1.16921670e-01  7.19770047e-02
   2.43422388e-02  2.52567900e-02 -2.13233920e-02 -5.23585254e-02
   5.97487376e-02 -4.88558797e-02 -1.56150508e-02 -7.61682620e-02
   6.35397412e-02  9.71609291e-02 -2.44206171e-02  4.97475146e-02
  -1.29947561e-02 -2.41964679e-02 -5.73416848e-02  3.11511024e-02
   8.38848806e-03 -1.37117077e-02  3.17494546e-02 -1.77651068e-03
   6.57610626e-02 -2.07741391e-02 -5.88045816e-02  3.52746429e-02
   1.70885351e-02 -1.56424146e-02  2.09092924e-02 -2.26038547e-02
  -1.19656838e-02 -7.75194711e-03 -3.62589701e-03  1.37779418e-02
   2.15347143e-02  1.00091759e-02 -1.03889636e-02  9.68241847e

In [14]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')
#memprediksi nilai nilai untuk target target

predicted response:
[[ 3.98305633e-01]
 [ 5.35462428e-01]
 [-6.39732110e-02]
 [ 4.84612667e-01]
 [ 3.94728105e-01]
 [ 3.90948442e-01]
 [ 5.06429780e-01]
 [ 4.16506531e-01]
 [ 4.81897371e-01]
 [ 1.13516966e-01]
 [ 4.25453075e-01]
 [ 2.68785442e-01]
 [ 5.68904466e-01]
 [ 6.09200575e-01]
 [ 4.19747713e-01]
 [ 7.91511763e-01]
 [ 6.29358662e-01]
 [ 2.53167699e-01]
 [ 7.23951403e-02]
 [ 2.97776348e-01]
 [ 1.22962700e-01]
 [ 7.81156893e-02]
 [ 1.02604581e+00]
 [ 2.59663913e-01]
 [ 5.60916723e-01]
 [ 1.63375458e-03]
 [ 3.76584648e-01]
 [ 2.48266765e-01]
 [ 1.08115756e-01]
 [ 1.00804739e-01]
 [ 2.56675147e-01]
 [ 6.46551097e-02]
 [ 3.57241961e-01]
 [ 1.98244890e-01]
 [ 4.42774130e-01]
 [ 2.67836081e-01]
 [ 2.54131318e-01]
 [ 6.64207855e-01]
 [ 4.23614234e-01]
 [ 5.54372374e-01]
 [ 2.74441997e-01]
 [ 5.58224411e-01]
 [ 1.61451545e-01]
 [ 6.70302843e-01]
 [ 6.25605860e-01]
 [ 5.32416375e-01]
 [ 6.65404177e-01]
 [ 4.86013638e-01]
 [ 5.03699866e-01]
 [ 1.32516182e-01]
 [ 4.63917977e-01]
 [ 3.035746

In [15]:
print("Mean Absolute Error (MAE): ", mean_absolute_error(y, y_pred))
print("Mean Squared Error (MSE): ", mean_squared_error(y, y_pred))
print("R2: ", r2_score(y, y_pred))

Mean Absolute Error (MAE):  0.3107960022098704
Mean Squared Error (MSE):  0.14070613119024145
R2:  0.3779313649958821
